export const CREATE_SHOP_START = "CREATE_SHOP_START";
export const CREATE_SHOP_ERROR = "CREATE_SHOP_ERROR";
export const CREATE_SHOP_SUCCESS = "CREATE_SHOP_SUCCESS";

export const UPDATE_SHOP_START = "UPDATE_SHOP_START";
export const UPDATE_SHOP_ERROR = "UPDATE_SHOP_ERROR";
export const UPDATE_SHOP_SUCCESS = "UPDATE_SHOP_SUCCESS";

export const GET_SHOPS_BY_USER_START = "GET_SHOPS_BY_USER_START";
export const GET_SHOPS_BY_USER_ERROR = "GET_SHOPS_BY_USER_ERROR";
export const GET_SHOPS_BY_USER_SUCCESS = "GET_SHOPS_BY_USER_SUCCESS";

export const GET_CURRENT_SHOP_START = "GET_CURRENT_SHOP_START";
export const GET_CURRENT_SHOP_ERROR = "GET_CURRENT_SHOP_ERROR";
export const GET_CURRENT_SHOP_SUCCESS = "GET_CURRENT_SHOP_SUCCESS";